# Generated by Django 5.1.1 on 2024-10-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosage',
            name='time_to_take',
        ),
        migrations.AddField(
            model_name='dosage',
            name='number_of_times',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dosage',
            name='time_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosage',
            name='time_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosage',
            name='time_3',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
